###create class
POST http://localhost:3001/api/classes/create
Content-Type: application/json

{
  "id_disciplina": 3,
  "id_dia": 2,
  "hora": "14:00:00",
  "capacidad_max": 25
}


###delete class
PUT http://localhost:3001/api/classes/delete
Content-Type: application/json

{
  "classId": 1
}

###registertoClass

POST https://backturnero.onrender.com/api/classes/register
Authorization: Bearer 
Content-Type: application/json

{
  "userId": 4,
  "classId": 2,
  "fecha": "2025-06-10"
}


# Desanotar usuario a una clase
POST http://localhost:3001/api/classes/unregister
Content-Type: application/json

{
  "userId": 4,
  "classId": 10,
  "fecha": "2025-06-06"
}

#update class
PUT http://localhost:3001/api/classes/update
Content-Type: application/json

{
  "id_clase": 1,
  "hora": "19:00:00",
  "capacidad_max": 25,
  "id_disciplina": 2,
  "id_dia": 6

}
####presentes

PUT https://backturnero.onrender.com/api/classes/update-attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjo2LCJlbWFpbCI6InNvbHN2N0BnbWFpbC5jb20iLCJpZF9yb2wiOjIsIm5vbWJyZSI6IlNvbCIsImlkX2VzdGFkbyI6MSwiaWF0IjoxNzU5Nzg5NzMwLCJleHAiOjE3NTk3OTMzMzB9.6qRkMj7JvjkRAscUv41Xd0t6hChK32lXMQR-IVltdQM
Content-Type: application/json

{
  "id_clase": 2,
  "fecha": "2025-10-07",
  "asistencias": [
    { "id_usuario": 4, "presente": true }
    ]
}
