###create class
POST http://localhost:3001/api/classes/create
Content-Type: application/json

{
  "id_disciplina": 3,
  "id_dia": 2,
  "hora": "14:00:00",
  "capacidad_max": 25
}


###delete class
PUT http://localhost:3001/api/classes/delete
Content-Type: application/json

{
  "classId": 1
}

###registertoClass

POST https://backturnero.onrender.com/api/classes/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjo0LCJlbWFpbCI6ImxhdUBleGFtcGxlLmNvbSIsImlkX3JvbCI6Mywibm9tYnJlIjoiTGF1dGFybyBCdXN0YW1hbnRlIiwiaWRfZXN0YWRvIjoxLCJpYXQiOjE3NTk3ODczMTksImV4cCI6MTc1OTc5MDkxOX0.ny4j2m_tG_GkOb-Dt-ZdkhfXJHNa_EN96mmojL1qwm0
Content-Type: application/json

{
  "userId": 4,
  "classId": 2,
  "fecha": "2025-10-06"
}


# Desanotar usuario a una clase
POST http://localhost:3001/api/classes/unregister
Content-Type: application/json

{
  "userId": 4,
  "classId": 10,
  "fecha": "2025-06-06"
}

#update class
PUT http://localhost:3001/api/classes/update
Content-Type: application/json

{
  "id_clase": 1,
  "hora": "19:00:00",
  "capacidad_max": 25,
  "id_disciplina": 2,
  "id_dia": 6

}