POST http://localhost:3001/api/planes/create
Content-Type: application/json

{
  "name": "Crossfit Semanal",
  "description": "6 Creditos Semanales para crossfit",
  "price": 30000,
  "totalCredits": 16,
  "disciplines": [1]
}
