### 🔹 Obtener cuotas activas de un usuario
GET http://localhost:3001/api/payments/active-fees?id_usuario=6
Content-Type: application/json


### 🔹 Registrar nueva cuota (usa créditos y monto del plan automáticamente)
POST http://localhost:3001/api/payments/register-fee
Content-Type: application/json

{
  "id_usuario": 4,
  "id_plan": 4,
  "metodo_pago": "efectivo",
  "pagado": true
}


### 🔹 Registrar nueva cuota pero dejarla pendiente (sin pagar)
POST https://backturnero.onrender.com/api/payments/register-fee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjo2LCJlbWFpbCI6InNvbHN2N0BnbWFpbC5jb20iLCJpZF9yb2wiOjIsIm5vbWJyZSI6IlNvbCIsImlkX2VzdGFkbyI6MSwiaWF0IjoxNzU5Nzg3NTEzLCJleHAiOjE3NTk3OTExMTN9.GSUBZ-hO1u-x-MsjLyYquUwDS8oG8WYVmBztOGvvQIk


{
  "id_usuario": 4,
  "id_plan": 1,
  "metodo_pago": "transferencia",
  "pagado": true
}


### 🔹 Pagar una cuota pendiente
POST http://localhost:3001/api/payments/pay-fee
Content-Type: application/json

{
  "id_cuota": 6,
  "metodo_pago": "efectivo"
}
