#create discpline
POST http://localhost:3001/api/disciplinas/create
Content-Type: application/json

{
  "name": "Yoga"
}

### Delete discipline
PUT http://localhost:3001/api/disciplinas/delete
Content-Type: application/json

{
  "disciplineId": 2
}