##admin
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "ivomonti1@gmail.com",
  "password": ""
}

###profe
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "solsv7@gmail.com",
  "password": ""
}
###alumno
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "lau@example.com",
  "password": ""
}