##admin
POST https://backturnero.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "ivomonti1@gmail.com",
  "password": "1234567"
}

###profe
POST https://backturnero.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "solsv7@gmail.com",
  "password": "1234567"
}
###alumno
POST https://backturnero.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "lau@example.com",
  "password": "1234567"
}