

###
POST http://localhost:3001/api/mp/preference-by-plan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxMSwiZW1haWwiOiJqb2Fnb21lekBnbWFpbC5jb20iLCJpZF9yb2wiOjMsIm5vbWJyZSI6IkpvYSBHb21leiIsImlkX2VzdGFkbyI6MSwiaWF0IjoxNzY3MDQ0NzI4LCJleHAiOjE3NjcwNDgzMjh9.Gasbf-kPbM0xpyWJcsf6gxP7at_JPmPUUUc-kKGKHA0
Content-Type: application/json

{
  "id_plan": 1
}