### Crear producto
POST http://localhost:3001/api/products/create
Content-Type: application/json

{
  "nombre": "Powerade Frutos Rojos",
  "descripcion": "Bebida isotónica",
  "precio": 3000,
  "stock": 20
}


### Obtener productos
GET http://localhost:3001/api/products/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjo3LCJlbWFpbCI6Iml2b21vbnRpMUBnbWFpbC5jb20iLCJpZF9yb2wiOjEsIm5vbWJyZSI6Ikl2byIsImlkX2VzdGFkbyI6MSwiaWF0IjoxNzYyMTEyNDQyLCJleHAiOjE3NjIxMTYwNDJ9.tlGTO36cNOzgiIKBdBuhi7p12TqXaLIGXSFJ8kVtE6w


### Eliminar producto
DELETE http://localhost:3001/api/products/delete/4

### Actualizar solo el precio
PUT http://localhost:3001/api/products/update
Content-Type: application/json

{
  "id_producto": 2,
  "precio": 2000
}

### Actualizar precio y stock
PUT http://localhost:3001/api/products/update
Content-Type: application/json

{
  "id_producto": 1,
  "precio": 18000,
  "stock": 50
}

### Actualizar nombre y descripción
PUT http://localhost:3001/api/products/update
Content-Type: application/json

{
  "id_producto": 1,
  "nombre": "Creatina Monohidratada",
  "descripcion": "Creatina de alta pureza"
}
