PUT http://localhost:3001/api/planes/update
Content-Type: application/json

{
  "planId": 1,
  "name": "Crossfit 12 C",
  "description": "3 creditos semanales Crossfit",
  "price": 25000,
  "totalCredits": 12
}
