### Actualizar datos de un usuario
PUT http://localhost:3001/api/usuarios/update
Content-Type: application/json

{
  "id_usuario": 4,
  "nombre": "Lautaro B.",
  "email": "lauti_b@example.com",
  "dni": "47000000",
  "celular": "1133440000"
}
